const $=id=>document.getElementById(id);
const canvas=$('preview'),ctx=canvas.getContext('2d');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let manifest=null,images={},clip='idle',frame=0,time=0,travel=0,last=0,playing=!reduced,direction=1,dungeon=true,ready=false,animationId=0;
const environment={};
function loadImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('部分画面素材没有载入，请重新加载。'));image.src=url;});}
function setPlaying(value){playing=value;$('play').textContent=value?'暂停':'播放';$('play').setAttribute('aria-label',value?'暂停播放':'开始播放');}
function current(){return manifest?.clips[clip];}
function cycleTravel(){const data=current();return (data?.cycleTravelPixels||0)*90/manifest.bodyHeight;}
function detailHeight(){const bounds=manifest.alphaBounds||[0,0,manifest.width,manifest.height];const above=manifest.anchorY-bounds[1],below=bounds[3]-manifest.anchorY,left=manifest.anchorX-bounds[0],right=bounds[2]-manifest.anchorX;return manifest.bodyHeight*Math.min(270/manifest.bodyHeight,315/Math.max(1,above),80/Math.max(1,below),205/Math.max(1,left,right));}
function selectClip(name){if(!manifest?.clips[name])return;clip=name;frame=0;time=0;travel=0;$('scrub').max=current().frames-1;document.querySelectorAll('[data-clip]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.clip===name)));draw();}
function seek(value){if(!ready)return;frame=Math.max(0,Math.min(current().frames-1,value));time=frame/current().fps;travel=frame/current().frames*cycleTravel();setPlaying(false);draw();}
function drawCharacter(x,y,height){const data=current(),w=manifest.width,h=manifest.height;const scale=height/manifest.bodyHeight;const sx=(frame%data.cols)*w,sy=Math.floor(frame/data.cols)*h;ctx.save();ctx.translate(x,y);ctx.scale(direction,1);ctx.drawImage(images[clip],sx,sy,w,h,-manifest.anchorX*scale,-manifest.anchorY*scale,w*scale,h*scale);ctx.restore();}
function scene(){ctx.save();ctx.beginPath();ctx.rect(0,0,670,490);ctx.clip();ctx.fillStyle=dungeon?'#0f1c25':'#17232c';ctx.fillRect(0,0,670,490);
 if(dungeon){for(const [name,alpha] of [['far',1],['mid',.72],['near',.7]]){const image=environment[name];if(!image)continue;ctx.globalAlpha=alpha;ctx.drawImage(image,0,0,960,540);}ctx.globalAlpha=1;
  const tiles=environment.tiles,offset=((travel*direction)%96+96)%96;if(tiles)for(let x=-96;x<780;x+=32)for(let y=366;y<490;y+=32)ctx.drawImage(tiles,((Math.floor(x/32)%3+3)%3)*32,y===366?0:32,32,32,Math.round(x-offset),y,32,32);
 }else{ctx.fillStyle='#12202a';ctx.fillRect(0,367,670,123);}
 ctx.fillStyle='#728891';ctx.globalAlpha=.25;ctx.fillRect(0,366,670,1);ctx.globalAlpha=1;ctx.fillStyle='#01080b88';ctx.beginPath();ctx.ellipse(336,367,26,5,0,0,Math.PI*2);ctx.fill();drawCharacter(336,367,90);ctx.restore();}
function draw(){if(!ready||!ctx)return;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,1120,490);scene();ctx.save();ctx.beginPath();ctx.rect(670,0,450,490);ctx.clip();ctx.fillStyle='#131e26';ctx.fillRect(670,0,450,490);ctx.fillStyle='#22343f';ctx.fillRect(705,394,380,1);ctx.fillStyle='#030b0f80';ctx.beginPath();ctx.ellipse(892,395,60,8,0,0,Math.PI*2);ctx.fill();drawCharacter(892,395,detailHeight());ctx.restore();ctx.fillStyle='#30424b';ctx.fillRect(670,0,1,490);$('scrub').value=frame;$('counter').value=`${String(frame+1).padStart(2,'0')} / ${current().frames}`;}
function tick(ms){const delta=last?Math.min((ms-last)/1000,.1):0;last=ms;if(ready&&playing&&!document.hidden){const data=current();const duration=data.frames/data.fps,step=delta*Number($('speed').value);time+=step;travel+=step/duration*cycleTravel();if(time>=duration+(data.loop?0:.55))time%=duration+(data.loop?0:.55);frame=Math.min(data.frames-1,Math.floor(time*data.fps));draw();}animationId=requestAnimationFrame(tick);}
async function init(){try{const response=await fetch('./assets/preview.json',{cache:'no-cache'});if(!response.ok)throw Error('动作信息未能载入，请重新加载。');manifest=await response.json();manifest.bodyHeight??=manifest.displayHeight;if(!(manifest.width>0&&manifest.height>0&&manifest.bodyHeight>0))throw Error('动作素材尺寸不正确。');
 await Promise.all(Object.entries(manifest.clips).map(async([key,data])=>{const image=await loadImage('./assets/'+data.image);if(!(data.frames>0&&data.fps>0&&data.cols>0)||image.width<data.cols*manifest.width||image.height<Math.ceil(data.frames/data.cols)*manifest.height)throw Error('动作帧不完整，请重新加载。');images[key]=image;}));
 await Promise.all(['far','mid','near','tiles'].map(async key=>{environment[key]=await loadImage('../assets/environment/'+key+'.png');}));ready=true;$('loading').hidden=true;selectClip(clip);setPlaying(playing);animationId=requestAnimationFrame(tick);
 }catch(error){$('loadMessage').textContent=error.message;$('retry').hidden=false;document.querySelectorAll('.transport button,.transport select,.clips button,#scrub').forEach(control=>control.disabled=true);}}
document.querySelectorAll('[data-clip]').forEach(button=>button.addEventListener('click',()=>selectClip(button.dataset.clip)));
$('play').onclick=()=>setPlaying(!playing);$('previous').onclick=()=>seek(frame-1);$('next').onclick=()=>seek(frame+1);$('scrub').oninput=event=>seek(Number(event.target.value));$('flip').onclick=()=>{direction*=-1;draw();};$('backdrop').onclick=()=>{dungeon=!dungeon;$('backdrop').textContent=dungeon?'地牢背景':'素色背景';$('backdrop').setAttribute('aria-pressed',String(dungeon));draw();};$('retry').onclick=()=>location.reload();
window.addEventListener('keydown',event=>{if(event.target.closest('button,input,select,a'))return;if(!ready)return;if(event.code==='Space'){event.preventDefault();setPlaying(!playing);}if(event.code==='ArrowLeft'){event.preventDefault();seek(frame-1);}if(event.code==='ArrowRight'){event.preventDefault();seek(frame+1);}});
document.addEventListener('visibilitychange',()=>{last=0;});window.addEventListener('pagehide',()=>cancelAnimationFrame(animationId),{once:true});init();
